# Generated by Django 2.2.7 on 2019-11-18 13:02

from django.db import migrations, models
import mysite.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=256)),
                ('myfile', models.FileField(upload_to=mysite.core.models.user_directory_path)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
